version: '0.1'

services:
  postgres:
    image: postgres:14.4-alpine
    container_name: hotelRentalDB
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgresVolume:/var/lib/postgresql/data