logging:
  level:
    org:
      springframework: ERROR

spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode=off:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation=true:


  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    url: "jdbc:postgresql://localhost:5433/postgres"
    username: "postgres"
    password: "postgres"

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}


admin:
  login: admin
  password: admin

tasks:
  checkExpiredRents:
    cron: "1 * * * * ?"
    enabled: "true"